language: node_js
node_js:
- '0.11'
- '0.10'
before_script: 
  - cd js/angular
  - gem install compass 
  - npm install -g bower
  - bower install --config.interactive=false
  - npm install
  - npm install grunt-cli
  - grunt build
env:
  global:
  - secure: WYS+4VfIdo+o24x3pGHPtUtyvRD8lUMhGKtBi+6KQl1t2D4focDMsrBlt260LhS4d2gWuaScQ8+Wi56jp+eksRnTScBlDtoyVxWEjfM1cSj0aW7BkpKl8SQI5o6+sMIZbOhuwevfVQSMhm2jjLJkUMQ9ElNQ7tfPBARykFFjVTg=
  - secure: LmHRe4P2FtvpRZH7OvGqIoWOamu6ht9c86ZOJpfEYlpUf7vsDpllAZkJYU1qbn5DL+pwUZ6POi5Ewe3t+f7XKfb+NVN2ZqKJ+gcCV9PQsZBfhOhfi5XEXHWpnlKDEsJaJewTRH4BRnJQCMQq6Tfb1MFjIP1msWeVyoD4WHDCNbI=
